### ISSUE TITLE
`rootAssetPath` usage

### ISSUE THREAD

**Issue by bradrobertson** [nickjj/manifest-revision-webpack-plugin#2]
Thought I'd just log a separate question as it's not *really* related to the previous one.

So I'm getting a compiled asset manifest file by pointing the `rootAssetPath` to the directory where webpack is ultimately outputting files into, but I'm a bit confused as to why we need this config:

My understanding (which is admittedly *very* limited) of a webpack plugin is that it would be fed, as input, a stream of the individual files that are being compiled, that it can then use to do its thing (output/munge etc to some file or another stream etc). This at least is how gulp works, so I could be completely out to lunch.

So if I'm understanding things properly, I imagined that the plugin would already know which files are being compiled (which would be the chunks sent through in the output), such that it could generate a manifest file for those outputted files. Why then do we need to specify the `rootAssetPath`? Shouldn't the plugin *know* which files it needs to add into the manifest? Am I completely misunderstanding how plugins should work?

**Comment by nickjj** [comment]
It needs the `rootAssetPath` because I use it internally to walk that path which detects assets that aren't currently listed under the `entry` section of the webpack config.

You might have let's say 1 javascript entry file and a few stylesheets (your main app, some vendor sheets, etc.). This is fine and dandy but what happens if you have 40 images? It would be unreasonable to have to keep a list of images there but without it being listed there then webpack really doesn't understand what to do with those files.

To overcome that I walk the root path and ignore anything in `ignorePaths`. For each file it finds, it internally calls `webpack.PrefetchPlugin` on the asset path. This lets us tag the file with the md5 or whatever you select in your webpack config (outside the scope of this plugin) and have it emit the file.

In my latest Flask project I only have it set to walk images because fonts tend to be versioned by vendors and your scripts/stylesheets are accounted for in the `entry` of your webpack config.

Here's a snippet of how I use this plugin atm:

```
        new ManifestRevisionPlugin(path.join('build', 'manifest.json'), {
            rootAssetPath: './testproject/assets',
            ignorePaths: ['/fonts', '/styles', '/scripts']
        })
```

**Comment by bradrobertson** [comment]
Ah ok, this makes sense. I guess in my head I just imagined all assets being run through webpack. Thanks for the clarification. I'll try out the new format option today (for the other issue)
