### ISSUE TITLE
Questions about the test_app

### ISSUE THREAD

**Issue by JiDai** [nickjj/manifest-revision-webpack-plugin#34]
Hi,
I tried to run your test app and I have two questions : 
- Why `context=' + rootAssetPath + '&` in loader configuration
- Why do you `ignorePaths: ['/styles', '/scripts']`

I have many many error in SASS files.

**Comment by nickjj** [comment]
Hi,

1. Which test app are you talking about?

2. You can ignore those paths because they are already being processed by webpack. This plugin can then handle images and whatever other assets you want md5 tagged. Of course if your application uses different paths for your CSS and JS files, you'll want to change those `ignorePaths`.

**Comment by JiDai** [comment]
https://github.com/nickjj/flask-webpack/tree/master/flask_webpack/tests/test_app

**Comment by nickjj** [comment]
`'file?context=' + rootAssetPath + '&name=[path][name].[hash].[ext]',`

^ This informs webpack where your root asset path is located and defines how the filename will be written to disk. This part of the config is webpack specific and isn't something special about this plugin.

**Comment by JiDai** [comment]
Ok thanks
